# Generated by Django 5.2.12 on 2026-03-04 15:07

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "image",
                    filer.fields.image.FilerImageField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slides",
                        to=settings.FILER_IMAGE_MODEL,
                        verbose_name="Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайды",
                "ordering": ["order"],
            },
        ),
    ]
